"""
Title: volstats definitions
"""
volstat_definitions = {
    'fatscore_baremaxtoraw': 'Fatscore is the average area per unit time between two line graphs A and B.  For every value on the x-axis (date), |A_x - B_x|/B_x is calculated, where A_x/B_x is the y-value at point x on graph A/B respectively.  Thus, the fatscore_AtoB equals the average of the set of {|A_x - B_x|/B_x for all x on the x-axis}.',
    'fatscore_baremaxtobaremin': 'Fatscore is the average area per unit time between two line graphs A and B.  For every value on the x-axis (date), |A_x - B_x|/B_x is calculated, where A_x|B_x is the y-value at point x on graph A|B respectively.  Thus, the fatscore_AtoB equals the average of the set of {|A_x - B_x|/B_x for all x on the x-axis}.',
    'drop_mag': 'Drop_mag measures how much the actual price is below the baremaxraw price on average, expressed as a proportion of the baremaxraw price.  This is calculated by averaging the set of all (actualprice_i - baremaxprice_i)/baremaxprice_i, where i is a point on the x-axis where that expression is nonzero.',
    'drop_prev': 'Drop_prev measures how often the actual price of a stock does not equal the baremaxraw price of the stock, expressed as a proportion of the entire date range in question.  A drop_prev of 0.70, for example, means the actual price of the stock is below the baremaxprice of the stock 70% of the time.',
    'dropscore': 'The dropscore is simply the drop_mag * drop_prev.  See drop_mag and drop_prev column headers for their respective meanings.',
    'dropscoreratio_Dow Jones': 'The dropscore ratio is the ratio of the dropscore of a given stock to a chosen benchmark.  For example, dropscoreratio_NASDAQ is the ratio of the dropscore of the stock in question to the dropscore of the NASDAQ.  Thus, a dropscoreratio of 1 means the stock does not dip below its own baremaxraw price anymore frequently and drastically than NASDAQ.  One could interpret this as one measure of how volatile the stock is as compared to the benchmark chosen.',
    'dropscoreratio_S&P 500': 'The dropscore ratio is the ratio of the dropscore of a given stock to a chosen benchmark.  For example, dropscoreratio_NASDAQ is the ratio of the dropscore of the stock in question to the dropscore of the NASDAQ.  Thus, a dropscoreratio of 1 means the stock does not dip below its own baremaxraw price anymore frequently and drastically than NASDAQ.  One could interpret this as one measure of how volatile the stock is as compared to the benchmark chosen.',
    'dropscoreratio_NASDAQ': 'The dropscore ratio is the ratio of the dropscore of a given stock to a chosen benchmark.  For example, dropscoreratio_NASDAQ is the ratio of the dropscore of the stock in question to the dropscore of the NASDAQ.  Thus, a dropscoreratio of 1 means the stock does not dip below its own baremaxraw price anymore frequently and drastically than NASDAQ.  One could interpret this as one measure of how volatile the stock is as compared to the benchmark chosen.'
    }
